name: CPack
inputs:
  config_dir:
    description: Directory in which the CPackConfig.cmake is located.
    default: out-cmake
    required: true
  output_dir:
    description: Directory where CPack outputs packages.
    default: out-cpack
    required: true
runs:
  using: composite
  steps:
    - uses: addnab/docker-run-action@v3
      with:
        image: fackop/ppdocker
        options: -v ${{ github.workspace }}:/workspace -w /workspace
        run: cpack --config ${{ inputs.config_dir }}/CPackConfig.cmake -B ${{ inputs.output_dir }}
